spring:
  application:
    name: "geocoder api"
yandex:
    baseUrl: "https://geocode-maps.yandex.ru/1.x/"
    apiKey: ${API_KEY}
    connectionTimeout: 30
    readTimeout: 30
logging:
  level:
    root: info
